# Generated by Django 6.0.1 on 2026-01-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="salary_range",
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
