# Generated by Django 6.0.1 on 2026-01-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Backend", "0002_alter_job_salary_range"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="salary_range",
            field=models.CharField(max_length=20),
        ),
    ]
