# Generated by Django 6.0.1 on 2026-02-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Backend", "0003_alter_job_salary_range"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="About",
            field=models.TextField(blank=True, null=True),
        ),
    ]
